### ISSUE TITLE
ftw run: "FsExtra error: The system cannot find the path specified. (os error 3)"

### ISSUE THREAD

**Issue by photex** [macalimlim/ftw#1]
I'm on Windows and godot is in my PATH; I'm able to run it from the command line.

I've created a new project: `ftw new foo`. Then I try to run it with `cd foo; ftw run`; and I get the following error after it successfully builds: "FsExtra error: The system cannot find the path specified. (os error 3)".

**Comment by photex** [comment]
Ah, I see now that this is happening in the build step:

```
c:\projects\kopernikus\depot\infra\godot-kcp>ftw build
Project is valid...
    Finished dev [unoptimized + debuginfo] target(s) in 1.90s
FsExtra error: The system cannot find the path specified. (os error 3)
```

Because... no apparent windows support at the moment. If I run godot manually I see as well that it doesn't find the dll.

**Comment by photex** [comment]
Resolved with an update to the template: https://github.com/godot-rust/godot-rust-template/pull/33

**Comment by macalimlim** [comment]
Hi @photex , thankyou for filing this issue. In order for the windows targets to work in ftw, changes must be made to the godot-rust-template first, then remove the windows targets from `targets_to_filter` vector from ftw_command.rs. If you want you could work on this issue and file a PR.

**Comment by Bromeon** [comment]
Is this really fixed? I just tried to install latest main as follows:
```
cargo install --git https://github.com/macalimlim/ftw --branch main
```
I previously had the published version from crates installed. It mentioned ```Replaced package `ftw v0.4.0` with `ftw v0.4.0 (https://github.com/macalimlim/ftw?branch=main#2a9bca15)` (executable `ftw.exe`)```.

However, when I execute `ftw --version`, I still get `ftw 0.4.0`, not sure if that's just the output or if didn't actually install the latest version.

Anyway, on `ftw run` I get the following error:
```
> ftw run
Project is valid...
    Finished dev [unoptimized + debuginfo] target(s) in 0.16s
Error: Das System kann die angegebene Datei nicht finden. (os error 2)
```
which means "system can't find the specified file". Note that OS error is 2 and not 3 as above (could be localization, whatever).

`ftw run` works.
Manually launching Godot with `godot.windows.tools.64.exe --path godot` also works.

Probably it's not finding the Godot executable, which one are you looking for?

**Comment by macalimlim** [comment]
Hi @Bromeon can you show using the `tree` command the generated game project? Is godot.exe on your $Path?

**Comment by Bromeon** [comment]
> Is godot.exe on your $Path?

Thanks, this seems to be the problem. I didn't have a `godot.exe` in PATH, only `godot.bat` (that I wrote myself) and the built version `godot.windows.tools.64.exe`.

What is the dispatch logic for executables? Would it make sense to look for the official name of the Godot binary name (i.e. not `godot.exe`) or just for `godot` (which would work for both .bat and .exe on Windows)?

**Comment by macalimlim** [comment]
`ftw` will try to execute a `godot` binary in $Path, I guess its different for batch files compared to exe files.I filed an issue here #9

**Comment by macalimlim** [comment]
does the batch file accept the same arguments as godot?

**Comment by Bromeon** [comment]
> does the batch file accept the same arguments as godot?

Yes, it's really just forwarding the arguments, I could as well have just renamed the .exe file.
`godot.bat`:
```bat
godot.windows.tools.64.exe %*
```

It should be enough on Windows to invoke `godot` (not `godot.exe`), that will work for both `.exe` and `.bat` files.
Or are you already doing that?
